name: 申请友链
description: 申请添加友链到本站
title: "友链申请："
labels: ["友链申请"]
body:
  - type: input
    id: name
    attributes:
      label: 网站名称
      description: 您的网站名称
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 网站描述
      description: 您的网站描述
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 网站链接
      description: 您的网站URL
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    id: avatar
    attributes:
      label: 头像链接
      description: 您的网站头像URL
      placeholder: https://example.com/avatar.png
    validations:
      required: true