name: 申请友链
description: 申请添加友情链接
labels: ["友链申请"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您申请友链！请填写以下信息。
  - type: input
    id: name
    attributes:
      label: 网站名称
      description: 您的网站名称
      placeholder: "例如：纸鹿摸鱼处"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 网站描述
      description: 一句话介绍您的网站
      placeholder: "例如：纸鹿至麓不知路，支炉制露不止漉"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 网站地址
      description: 您的网站URL
      placeholder: "例如：https://blog.zhilu.site/"
    validations:
      required: true
  - type: input
    id: avatar
    attributes:
      label: 头像地址
      description: 您的头像图片URL
      placeholder: "例如：https://www.zhilu.site/api/avatar.png"
    validations:
      required: true
