name: 选择操作类型
description: 请选择您要执行的操作类型
labels: ["待处理"]
body:
  - type: dropdown
    id: action-type
    attributes:
      label: 操作类型
      description: 请选择您要执行的操作
      options:
        - 申请友链
        - 添加捐赠
        - 正常议题
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 详细描述
      description: 请详细描述您的请求
    validations:
      required: true